AWSTemplateFormatVersion: '2010-09-09'

################################################################################
# Resources
################################################################################
Parameters:
  TargetType:
    Description: The registration type of the targets in this target group
    Type: String
    Default: instance
    AllowedValues:
      - instance
      - ip

################################################################################
# Resources
################################################################################
Resources:
  TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: code-deploy-demo-tg
      Protocol: HTTP
      Port: 80
      TargetType: !Ref TargetType
      VpcId:
        Fn::ImportValue:
          Fn::Join: ['-',['Fn::Sub':'${AWS::AccountId}','Fn::Sub':'${AWS::Region}','code-deploy-demo-vpc']]
  LoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: code-deploy-demo-alb
      SecurityGroups:
        - Fn::ImportValue: 
            Fn::Join: ['-',['Fn::Sub':'${AWS::AccountId}','Fn::Sub':'${AWS::Region}','code-deploy-demo-sg']]
      Subnets:      
        - Fn::ImportValue:
            Fn::Join: ['-',['Fn::Sub':'${AWS::AccountId}','Fn::Sub':'${AWS::Region}','code-deploy-demo-subnet1']]
        - Fn::ImportValue:
            Fn::Join: ['-',['Fn::Sub':'${AWS::AccountId}','Fn::Sub':'${AWS::Region}','code-deploy-demo-subnet2']]
      IpAddressType: ipv4
  Lister:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - TargetGroupArn: !Ref TargetGroup
          Type: forward
      LoadBalancerArn: !Ref LoadBalancer
      Port: 80
      Protocol: HTTP

################################################################################
# Outputs
################################################################################
Outputs:
  TargetGroupArn:
    Value: !Ref TargetGroup
    Export:
      Name: !Join ['-', ['Fn::Sub':'${AWS::AccountId}', 'Fn::Sub':'${AWS::Region}', 'code-deploy-demo-tg']]
