version: '3'
services:
  app:
    image: 172612068623.dkr.ecr.us-east-2.amazonaws.com/code-deploy-demo:latest
    ports:
      - "80:80"
    logging:
      driver: awslogs
      options: 
        awslogs-group: code-deploy-demo
        awslogs-region: us-east-2
        awslogs-stream-prefix: app
